In [1]:
import pandas as pd
# Straight from keras.io tutorial
import pandas as pd
import numpy as np
import os
import typing
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# To access local folder(s)/data on your own drive
from google.colab import drive

# The code starts here, this Neural Network in Python is just a script (from the looks of it)
# From: https://keras.io/examples/timeseries/timeseries_traffic_forecasting/

In [2]:
# DATA ACQUISITION SECTION :

# Instead mount the drive to get access to files.
drive.mount('/content/gdrive')

my_path = "/content/gdrive/Shareddrives/CPSC 4176 Project Spring 2023/UAV Data/" # THIS is your GDrive path

uav4_data = my_path + "UAV_4_Data_up.xlsx" # The specific file you are trying to access
rawdata = pd.read_excel(uav4_data)

Mounted at /content/gdrive

In [4]:
UAV_data = pd.read_excel(uav4_data, header=None
).to_numpy()

In [12]:
print(UAV_data.shape)

#plt.figure(figsize=(18, 6))

rawdata.head()

(90237, 10)

,VehicleID,LaneID,Time(s),x-axis position(m),Distance from upper Lane line(m),Distance from lower lane line(m),Speed(m/s),Acceleration(m/s^2),VehicleLength(meter),VehicleWidth(meter)
0,190,1,12.03213,356.155000,0.886318,2.561187,14.354737,0.013802,4.480434,1.79063
1,190,1,12.06546,355.676557,0.886607,2.558093,14.355196,-0.015969,4.480434,1.79063
2,190,1,12.09879,355.198098,0.886847,2.555047,14.354664,0.070083,4.480434,1.79063
3,190,1,12.13212,354.719657,0.887034,2.552055,14.356998,0.094688,4.480434,1.79063
4,190,1,12.16545,354.241138,0.887155,2.549129,14.360151,0.117653,4.480434,1.79063

In [15]:
# searches for specific VehicleID and extracts all data for that vehicle
search_vehicle_id = 190
vehicle_data = rawdata.loc[rawdata['VehicleID'] == search_vehicle_id]
vehicle_data

,VehicleID,LaneID,Time(s),x-axis position(m),Distance from upper Lane line(m),Distance from lower lane line(m),Speed(m/s),Acceleration(m/s^2),VehicleLength(meter),VehicleWidth(meter)
0,190,1,12.03213,356.155000,0.886318,2.561187,14.354737,1.380183e-02,4.480434,1.79063
1,190,1,12.06546,355.676557,0.886607,2.558093,14.355196,-1.596906e-02,4.480434,1.79063
2,190,1,12.09879,355.198098,0.886847,2.555047,14.354664,7.008347e-02,4.480434,1.79063
3,190,1,12.13212,354.719657,0.887034,2.552055,14.356998,9.468816e-02,4.480434,1.79063
4,190,1,12.16545,354.241138,0.887155,2.549129,14.360151,1.176525e-01,4.480434,1.79063
...,...,...,...,...,...,...,...,...,...,...
444,190,1,26.83065,134.101380,3.097898,0.030177,15.003697,-4.585401e-02,4.480434,1.79063
445,190,1,26.86398,133.601306,3.094921,0.024845,15.002170,-1.528467e-02,4.480434,1.79063
446,190,1,26.89731,133.101284,3.091913,0.019545,15.001661,7.361479e-11,4.480434,1.79063
447,190,1,26.93064,132.601279,3.088889,0.014261,15.001661,-1.528467e-02,4.480434,1.79063
448,190,1,26.96397,132.101273,3.085833,0.009009,15.001152,-4.585401e-02,4.480434,1.79063